### ISSUE TITLE
Make `othertext_lookup` extensible 

### ISSUE THREAD

**Issue by collinschwantes** [ecohealthalliance/ohcleandat#15]
`othertext_lookup` currently is a hardcoded tibble, it might be better to be able to make `othertext_lookup` a function for creating the tibble in the appropriate form. 

Maybe `create_freetext_log` then accepts objects of class `othertext_lookup` as a parameter. 

```
ot_lookup_table <- othertext_lookup(field_names,free_text_field_names) 
create_freetext_log(..., othertext_lookup = ot_lookup_table)
```

**Comment by deanmarchiori** [comment]
Fixed, closing
